app <- ShinyDriver$new("../", seed = 7038)
app$snapshotInit("density-histogram")

app$setInputs(which_panel = "plots", chart_type = "histogram")
app$uploadFile(infile = "mpg.csv")
# Input '`shinyjs-resettable-y_label`' was set, but doesn't have an input binding.
app$setInputs(x = "displ")
app$setInputs(do_plot = "click")
app$snapshot()
app$setInputs(z = "cyl")
app$setInputs(do_plot = "click")
app$snapshot()
app$setInputs(chart_type = "density")
app$setInputs(do_plot = "click")
app$snapshot()
